name: Telegram Signals

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install telethon

      - name: Run signal script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
          CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
        run: python send_signal.py
